services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=supa_db'
      - 'POSTGRES_PASSWORD=supa123'
      - 'POSTGRES_USER=supa'
    ports:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - supa_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U supa -d supa_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: 'redis:7-alpine'
    ports:
      - '6379'
    volumes:
      - redis_data:/data
    networks:
      - supa_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  namesrv:
    image: apache/rocketmq:5.1.4
    command: sh mqnamesrv
    ports:
      - '9876'
    volumes:
      - namesrv_data:/home/rocketmq/logs
    networks:
      - supa_net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9876"]
      interval: 10s
      timeout: 5s
      retries: 5

  broker:
    image: apache/rocketmq:5.1.4
    command: sh mqbroker -n namesrv:9876
    ports:
      - '10909'
      - '10911'
      - '10912'
    volumes:
      - broker_data:/home/rocketmq/logs
      - broker_store:/home/rocketmq/store
    environment:
      - NAMESRV_ADDR=namesrv:9876
    depends_on:
      namesrv:
        condition: service_healthy
    networks:
      - supa_net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "10909"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  namesrv_data:
  broker_data:
  broker_store:

networks:
  supa_net:
    driver: bridge 