spring:
  application:
    name: supa-demo
  docker:
    compose:
      # 启用 Docker Compose 支持
      enabled: true
      # 指定 compose 文件位置
      file: compose.yaml
      # 启动时等待服务健康检查
      lifecycle-management: start_only
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${spring.docker.compose.ports.postgres:54691}/supa_db
    username: supa
    password: supa123
  
  data:
    redis:
      host: localhost
      port: ${spring.docker.compose.ports.redis:50003}
      database: 0

server:
  port: 8081